### PR TITLE
add allow_new global configuration (bool) option

### PR DESCRIPTION
**Pull request by gnawhleinad**
to prevent the creation of new tabs and use strictly what is defined in
the `tab.yml` repo / workspace.

### CODE REVIEW

**Comment by gnawhleinad** [comment]
- [ ] need to fix `--check`

**Comment by gnawhleinad** [comment]
> * [ ]  need to fix `--check`

🤔 , actually, I think this is a separate issue. It looks like the global `tab.yml` **needs** an explicit `workspace` definition. I was using a global `tab.yml` with just:

```yaml
allow_new: false
```

**Comment by austinjones** [comment]
Hey @gnawhleinad, this looks cool!  I just wrapped up the final v0.5.X hotfix so I'll take a look at this tomorrow night and I'll include it in v0.6.0.

**Comment by austinjones** [comment]
Thanks for the PR!  I think I might move the option to `fuzzy: new_tab`.  But the code looks great!

**Comment by gnawhleinad** [comment]
> Thanks for the PR! I think I might move the option to `fuzzy: new_tab`.

:+1:, works for me!

> But the code looks great!

:bow:!

**Pull request merged**
