### PR TITLE
Fix an integer underflow bug that could cause the scrollback buffer to be perpetually emptied

### PR DESCRIPTION
**Pull request by austinjones**

### CODE REVIEW

**Comment by jrop** [comment]
@austinjones Can you let me know when this is ready to test and I'll give it a whirl? (I just checked the branch out, built the project and tested it out, and I still get the problem described in #262

**Comment by austinjones** [comment]
Hey @jrop, did you do `tab --shutdown` before testing?  If you had a v0.5.3 daemon running, that wouldn't include this change.

If it still happens, I'll need to do some more bug hunting..

**Comment by jrop** [comment]
@austinjones yes, I did `tab -W` and also tried `tab --shutdown`, and then created some new tabs, tried switching between them, and it still happened. (I made certain to checkout this branch, as well):

```sh
git clone ...
cd tab-rs
git checkout austinjones-scrollback-underflow
cd tab/
cargo install --path .
tab --shutdown
tab tab1
tab tab2
# ... try switching between tab1/tab2 multiple times
```

**Comment by austinjones** [comment]
Allright.  There is definitely something else going on then.  I'll keep looking.  This is a really tough one..

Could you try pulling the daemon log in debug mode?  It'd have a lot more info.  You can launch the daemon with debug logging enabled by running `tab --shutdown; tab --log debug foo; ctrl-T esc`.  Then you can call the client without debug logs and the daemon will keep on logging.

**Comment by jrop** [comment]
@austinjones Here's a few log lines that got printed when I observed this issue:

```
❯ tail daemon.log
16:23:33.164 DAE [INFO] Retasking subscription from TabId(1) to Some(TabId(2))
16:23:33.164 DAE [DEBUG] (13) tab_daemon::service::cli::subscription: subscription state: AwaitingScrollback(TabId(2), [])
16:23:33.164 DAE [DEBUG] (5) lifeline::channel::lifeline::receiver: RECV: Output(TabOutput { id: TabId(1), stdout: OutputChunk { index: 6728, data: [...] } })
16:23:33.164 DAE [DEBUG] (9) lifeline::channel::lifeline::receiver: RECV: Retask(TabId(1), Some(TabId(2)))
16:23:33.165 DAE [DEBUG] (9) tab_daemon::service::cli::subscription: subscription state: None
16:23:33.165 DAE [DEBUG] (4) tab_daemon::bus::cli: ListenerConnectionCarrier forwarding scrollback request on tab TabId(2)
16:23:33.165 DAE [DEBUG] (3) tab_daemon::service::cli: received Request: Subscribe(TabId(2))
16:23:33.165 DAE [DEBUG] (5) lifeline::channel::lifeline::receiver: RECV: Output(TabOutput { id: TabId(1), stdout: OutputChunk { index: 6728, data: [...] } })
16:23:33.165 DAE [DEBUG] (11) lifeline::channel::lifeline::receiver: RECV: Output(TabOutput { id: TabId(1), stdout: OutputChunk { index: 6728, data: [...] } })
16:23:33.175 DAE [DEBUG] (4) lifeline::channel::lifeline::receiver: RECV: Scrollback(PtyScrollback { scrollback: Mutex { data: ScrollbackBuffer { size: 6439, queue: [OutputChunk { index: 0, data: [...] }] } } })
16:23:33.213 DAE [DEBUG] (3) tab_daemon::service::cli: client subscribing to tab TabId(2)
16:23:33.213 DAE [DEBUG] (5) tab_daemon::service::cli::subscription: subscription state: AwaitingScrollback(TabId(2), [])
16:23:33.213 DAE [DEBUG] (11) lifeline::channel::lifeline::receiver: RECV: Output(TabOutput { id: TabId(1), stdout: OutputChunk { index: 6728, data: [27, 91, 49, 59, 49, 72, 27, 91, 50, 74, 27, 91, 49, 59, 49, 72] } })
16:23:33.221 DAE [DEBUG] (4) lifeline::channel::lifeline::receiver: RECV: Scrollback(TabScrollback { id: TabId(2), scrollback: PtyScrollback { scrollback: Mutex { data: <locked> } } })
16:23:33.228 DAE [DEBUG] (13) lifeline::channel::lifeline::receiver: RECV: Scrollback(TabScrollback { id: TabId(2), scrollback: PtyScrollback { scrollback: Mutex { data: ScrollbackBuffer { size: 6439, queue: [OutputChunk { index: 0, data: [...] }] } } } })
16:23:33.261 DAE [DEBUG] (3) tab_daemon::service::cli: received Request: ResizeTab(TabId(2), (110, 56))
16:23:33.261 DAE [INFO] Resizing tab 2 to (110, 56)
16:23:33.261 DAE [DEBUG] (3) tab_daemon::service::pty: resizing pty to (110, 56)
16:23:33.261 DAE [DEBUG] (5) lifeline::channel::lifeline::receiver: RECV: Subscribe(TabId(2))
16:23:33.261 DAE [DEBUG] (11) tab_daemon::service::cli::subscription: subscription state: None
16:23:33.261 DAE [DEBUG] (5) tab_daemon::service::cli::subscription: Ignoring subscription request for TabId(2)
16:23:33.269 DAE [DEBUG] (11) lifeline::channel::lifeline::receiver: RECV: Scrollback(TabScrollback { id: TabId(2), scrollback: PtyScrollback { scrollback: Mutex { data: <locked> } } })
16:23:33.277 DAE [DEBUG] (5) lifeline::channel::lifeline::receiver: RECV: Scrollback(TabScrollback { id: TabId(2), scrollback: PtyScrollback { scrollback: Mutex { data: ScrollbackBuffer { size: 6439, queue: [OutputChunk { index: 0, data: [...] }] } } } })
16:23:33.309 DAE [INFO] Received scrollback for tab TabId(2)
16:23:33.309 DAE [DEBUG] (5) tab_daemon::service::cli::subscription: tx subscription TabId(2), idx 0..4069, len 4069
16:23:33.309 DAE [DEBUG] (5) tab_daemon::service::cli::subscription: tx subscription TabId(2), data: "\e]4;0;rgb:15/15/15\e\\\e]4;1;rgb:fb/9f/b1\e\\\e]4;2;rgb:ac/c2/67\e\\\e]4;3;rgb:dd/b2/6f\e\\\e]4;4;rgb:6f/c2/ef\e\\\e]4;5;rgb:e1/a3/ee\e\\\e]4;6;rgb:12/cf/c0\e\\\e]4;7;rgb:d0/d0/d0\e\\\e]4;8;rgb:50/50/50\e\\\e]4;9;rgb:fb/9f/b1\e\\\e]4;10;rgb:ac/c2/67\e\\\e]4;11;rgb:dd/b2/6f\e\\\e]4;12;rgb:6f/c2/ef\e\\\e]4;13;rgb:e1/a3/ee\e\\\e]4;14;rgb:12/cf/c0\e\\\e]4;15;rgb:f5/f5/f5\e\\\e]4;16;rgb:ed/a9/87\e\\\e]4;17;rgb:de/af/8f\e\\\e]4;18;rgb:20/20/20\e\\\e]4;19;rgb:30/30/30\e\\\e]4;20;rgb:b0/b0/b0\e\\\e]4;21;rgb:e0/e0/e0\e\\\e]10;rgb:d0/d0/d0\e\\\e]11;rgb:15/15/15\e\\\e]12;7\e\\\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\e[38;5;237m⏎\e(B\e[m                                                                                                             \r⏎ \r\e[K\e[?2004h\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\r\r\e[J\e[1;36m☸ k8scluster (dev)\e[0m in \e[1;36m~\e[0m \e[1;34mtab tab3/\e[0m \r\n\e[1;32m❯\e[0m \e[K\r\n\e[30m\e(B\e[m\e[?2004l\e[?1004l\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\r\e[?1004h\e[38;5;237m⏎\e(B\e[m                                                                                                             \r⏎ \r\e[K\e[?2004h\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\r\r\e[J\e[1;36m☸ k8scluster (dev)\e[0m in \e[1;36m~\e[0m \e[1;34mtab tab3/\e[0m \r\n\e[1;32m❯\e[0m \e[K\r\n\e[30m\e(B\e[m\e[?2004l\e[?1004l\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\r\e[?1004h\e[38;5;237m⏎\e(B\e[m                                                                                                             \r⏎ \r\e[K\e[?2004h\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\r\r\e[J\e[1;36m☸ k8scluster (dev)\e[0m in \e[1;36m~\e[0m \e[1;34mtab tab3/\e[0m \r\n\e[1;32m❯\e[0m \e[K\r\n\e[30m\e(B\e[m\e[?2004l\e[?1004l\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\r\e[?1004h\e[38;5;237m⏎\e(B\e[m                                                                                                             \r⏎ \r\e[K\e[?2004h\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\r\r\e[J\e[1;36m☸ k8scluster (dev)\e[0m in \e[1;36m~\e[0m \e[1;34mtab tab3/\e[0m \r\n\e[1;32m❯\e[0m \e[K\r\n\e[30m\e(B\e[m\e[?2004l\e[?1004l\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\r\e[?1004h\e[38;5;237m⏎\e(B\e[m                                                                                                             \r⏎ \r\e[K\e[?2004h\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\r\r\e[J\e[1;36m☸ k8scluster (dev)\e[0m in \e[1;36m~\e[0m \e[1;34mtab tab3/\e[0m \r\n\e[1;32m❯\e[0m \e[Kl\b\e[38;2;204;102;102ml\e[30m\e(B\e[m\e[38;2;150;152;150ma \b\b\e[30m\e(B\e[m\e[38;2;204;102;102ms\e[30m\e(B\e[m\e[K\b\b\e[38;2;178;148;187mls\e[30m\e(B\e[m\e[38;2;150;152;150m \b\e[30m\e(B\e[m\b\b\e[38;2;178;148;187mexa\e[30m\e(B\e[m \e[38;2;129;162;190m--git\e[30m\e(B\e[m\r\n\e[30m\e(B\e[m\e[?2004l\e[?1004l\e]0;exa /Users/jonathan\a\e[30m\e(B\e[m\rAnne-Pro-II-Layout.json  \e[1;34mDropbox\e[0m                 \e[1;34mMusic\r\n"
16:23:33.309 DAE [DEBUG] (5) tab_daemon::service::cli::subscription: tx subscription TabId(2), idx 4069..6439, len 2370
16:23:33.309 DAE [DEBUG] (5) tab_daemon::service::cli::subscription: tx subscription TabId(2), data: "\e[?1004h\e[38;5;237m⏎\e(B\e[m                                                                                                             \r⏎ \r\e[K\e[?2004h\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\r\r\e[J\e[1;36m☸ k8scluster (dev)\e[0m in \e[1;36m~\e[0m \e[1;34mtab tab3/\e[0m \r\n\e[1;32m❯\e[0m \e[K\e]0;fish /Users/jonathan\a\e[30m\e(B\e[m\r\e[A\e[J\e[1;36m☸ k8scluster (dev)\e[0m in \e[1;36m~\e[0m \e[1;34mtab tab3/\e[0m \r\n\e[1;32m❯\e[0m \e[Kz\b\e[38;2;178;148;187mz\e[30m\e(B\e[m\e[38;2;150;152;150m \b\e[30m\e(B\e[m\e[38;2;178;148;187m \e[30m\e(B\e[m\b i\b\e[38;2;129;162;190m\e[4mi\e[30m\e(B\e[m\e[38;2;129;162;190m\e[4mn\e[30m\e(B\e[m\e[38;2;129;162;190m\e[4mf\e[30m\e(B\e[m\b\b\b\e[38;2;129;162;190minf\e[30m\e(B\e[m\e[38;2;129;162;190mr\e[30m\e(B\e[m\e[38;2;129;162;190ma\e[30m\e(B\e[m\r\n\e[30m\e(B\e[m\e[?2004l\e[?1004l\e]0;z /Users/jonathan\a\e[30m\e(B\e[m\r\e[?1004h\e[38;5;237m⏎\e(B\e[m                                                                                                             \r⏎ \r\e[K\e[?2004h\e]0;fish /Users/jonathan/...\a\e[30m\e(B\e[m\r\r\e[J\e[1;36m☸ k8scluster (dev)\e[0m in \e[1;36minfra\e[0m on \e[1;35m\u{e0a0} master\e[0m \e[1;31m[\$!?]\e[0m \e[1;34mtab tab3/\e[0m \r\n\e[1;32m❯\e[0m \e[Kt\b\e[38;2;178;148;187mt\e[30m\e(B\e[m\e[38;2;178;148;187ma\e[30m\e(B\e[m\b\b\e[38;2;204;102;102mta\e[30m\e(B\e[m\e[38;2;150;152;150mb \b\b\e[30m\e(B\e[m\e[38;2;204;102;102mb\e[38;2;150;152;150m \b\e[30m\e(B\e[m\b\b\b\e[38;2;178;148;187mtab\e[38;2;150;152;150m \b\e[30m\e(B\e[m\e[K\r\n\e[30m\e(B\e[m\e[?2004l\e[?1004l\e]0;tab /Users/jonathan/...\a\e[30m\e(B\e[m\r\e[?25h\e[?12l\e[?1049l\e[?1l\e>\e[?25l\e[1;1H❯ \e[1m\e[0m\e[K\e[2;1H  \e[1m0\e[0m\e[1m/\e[0m\e[1m0\e[0m\e[K\e[J\e[1;3H\e[?25h\e[?25l\e[1;1H❯ \e[1m\e[0m\e[K\e[2;1H  \e[1m0\e[0m\e[1m/\e[0m\e[1m0\e[0m\e[K\e[J\e[1;3H\e[?25h\e[?25l\e[1;1H❯ \e[1m\e[0m\e[K\e[2;1H  \e[1m3\e[0m\e[1m/\e[0m\e[1m3\e[0m\e[K\e[3;1H  \e[1mtab1/\e[0m\e[38;5;8m  \e[0m\e[K\e[4;1H  \e[1mtab2/\e[0m\e[38;5;8m  \e[0m\e[K\e[5;1H  \e[1mtab3/\e[0m\e[38;5;8m  \e[0m\e[K\e[J\e[1;3H\e[?25h\e[?25l\e[1;1H❯ \e[1m\e[0m\e[K\e[2;1H  \e[1m3\e[0m\e[1m/\e[0m\e[1m3\e[0m\e[K\e[3;1H\e[38;5;12m❯ \e[0m\e[38;5;12m\e[1mtab1/\e[0m\e[38;5;12m  \e[0m\e[K\e[4;1H  \e[1mtab2/\e[0m\e[38;5;8m  \e[0m\e[K\e[5;1H  \e[1mtab3/\e[0m\e[38;5;8m  \e[0m\e[K\e[J\e[1;3H\e[?25h\e[?25l\e[1;1H❯ \e[1m\e[0m\e[K\e[2;1H  \e[1m3\e[0m\e[1m/\e[0m\e[1m3\e[0m\e[K\e[3;1H  \e[1mtab1/\e[0m\e[38;5;8m  \e[0m\e[K\e[4;1H\e[38;5;12m❯ \e[0m\e[38;5;12m\e[1mtab2/\e[0m\e[38;5;12m  \e[0m\e[K\e[5;1H  \e[1mtab3/\e[0m\e[38;5;8m  \e[0m\e[K\e[J\e[1;3H\e[?25h\e[1;1H\e[2J\e[1;1H\e[?25h\e[?12l\e[?1049l\e[?1l\e>"
16:23:33.310 DAE [DEBUG] (5) tab_daemon::service::cli::subscription: subscription state: Selected(TabId(2), 6439)
16:23:33.416 DAE [DEBUG] (9) tungstenite::protocol: Received close frame: None
16:23:33.417 DAE [DEBUG] (9) tungstenite::protocol: Replying to close with Frame { header: FrameHeader { is_final: true, rsv1: false, rsv2: false, rsv3: false, opcode: Control(Close), mask: None }, payload: [] }
16:23:33.417 DAE [DEBUG] (11) lifeline::channel::lifeline::receiver: RECV: Output(OutputChunk { index: 6744, data: [...] })
16:23:33.418 DAE [DEBUG] (9) tab_websocket::service::connection: terminating - received close
16:23:33.418 DAE [DEBUG] (11) tab_daemon::service::pty::scrollback: scrollback appending stdout chunk 6744..6771 to existing chunk 4092..6744, size 6771
16:23:33.418 DAE [DEBUG] (3) lifeline::channel::lifeline::receiver: RECV: Output(OutputChunk { index: 6744, data: [...] })
16:23:33.418 DAE [DEBUG] (9) tab_websocket::service::connection: server loop terminated
16:23:33.418 DAE [DEBUG] (3) lifeline::channel::lifeline::receiver: RECV: Output(TabOutput { id: TabId(1), stdout: OutputChunk { index: 6744, data: [...] } })
16:23:33.419 DAE [DEBUG] (9) lifeline::service: OK WebsocketService/run
16:23:33.419 DAE [DEBUG] (9) lifeline::spawn: END WebsocketService/run ()
16:23:33.419 DAE [DEBUG] (9) lifeline::service: OK WebsocketConnectionBus/forward_recv
16:23:33.419 DAE [DEBUG] (9) lifeline::spawn: END WebsocketConnectionBus/forward_recv ()
16:23:33.419 DAE [DEBUG] (3) lifeline::channel::lifeline::receiver: RECV: Output(TabOutput { id: TabId(1), stdout: OutputChunk { index: 6744, data: [...] } })
16:23:33.420 DAE [DEBUG] (3) tab_daemon::service::cli::subscription: subscription state: Selected(TabId(2), 6439)
16:23:33.420 DAE [DEBUG] (9) lifeline::service: OK CliService/run
16:23:33.420 DAE [DEBUG] (9) lifeline::spawn: END CliService/run ()
16:23:33.420 DAE [DEBUG] (9) lifeline::service: OK ListenerService/connection_9/cli
16:23:33.420 DAE [DEBUG] (11) lifeline::channel::lifeline::receiver: RECV: Output(TabOutput { id: TabId(1), stdout: OutputChunk { index: 6744, data: [...] } })
16:23:33.420 DAE [DEBUG] (11) lifeline::spawn: CANCEL CliBus/output
16:23:33.420 DAE [DEBUG] (9) lifeline::spawn: END ListenerService/connection_9/cli ()
16:23:33.421 DAE [DEBUG] (9) lifeline::spawn: CANCEL CliBus/forward_tabs_state
16:23:33.421 DAE [DEBUG] (5) lifeline::spawn: CANCEL CliSubscriptionService/rx
16:23:33.421 DAE [DEBUG] (4) lifeline::spawn: CANCEL WebsocketConnectionBus/forward_send
16:23:33.421 DAE [DEBUG] (2) lifeline::spawn: CANCEL CliService/run
16:23:33.421 DAE [DEBUG] (3) lifeline::spawn: CANCEL CliService/run
16:23:33.421 DAE [DEBUG] (13) lifeline::spawn: CANCEL CliBus/input
```

**Comment by austinjones** [comment]
Thank you!!  This is so helpful :)

**Pull request closed without merging**
